/*
  (c) Copyright 2007 Hewlett-Packard Development Company, LP
  [See end of file]
  $Id: Vocab.java 1137 2007-04-13 15:06:06Z jeremy_carroll $
*/
package com.hp.hpl.jena.grddl.license;
/* CVS $Id: $ */

import com.hp.hpl.jena.rdf.model.Model;
import com.hp.hpl.jena.rdf.model.ModelFactory;
import com.hp.hpl.jena.rdf.model.Property;
import com.hp.hpl.jena.rdf.model.Resource;
 
/**
 * Vocabulary definitions from ../grddl/vocabularies/license.rdf 
 * @author Auto-generated by schemagen on 06 Mar 2007 16:18 
 */
public class Vocab {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://jena.hpl.hp.com/2007/03/license#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    /** <p>Some of the software which is the topic of the license agreement, is described 
     *  by the object literal. This should usually contain the name and version number 
     *  of the software.</p>
     */
    public static final Property software = m_model.createProperty( "http://jena.hpl.hp.com/2007/03/license#software" );
    
    /** <p>A licensee of the subject agreement has a user's account name given by the 
     *  object.</p>
     */
    public static final Property licensee = m_model.createProperty( "http://jena.hpl.hp.com/2007/03/license#licensee" );
    
    /** <p>A licensor of the subject agreement has a name given by the object literal.</p> */
    public static final Property licensor = m_model.createProperty( "http://jena.hpl.hp.com/2007/03/license#licensor" );
    
    /** <p>The subject agreement was made on the date specified.</p> */
    public static final Property agreementDate = m_model.createProperty( "http://jena.hpl.hp.com/2007/03/license#agreementDate" );
    
    /** <p>A class representing the act of an agreement, under the BSD license, being made.</p> */
    public static final Resource Agreement = m_model.createResource( "http://jena.hpl.hp.com/2007/03/license#Agreement" );
}


/*
    (c) Copyright 2007 Hewlett-Packard Development Company, LP
    All rights reserved.

    Redistribution and use in source and binary forms, with or without
    modification, are permitted provided that the following conditions
    are met:

    1. Redistributions of source code must retain the above copyright
       notice, this list of conditions and the following disclaimer.

    2. Redistributions in binary form must reproduce the above copyright
       notice, this list of conditions and the following disclaimer in the
       documentation and/or other materials provided with the distribution.

    3. The name of the author may not be used to endorse or promote products
       derived from this software without specific prior written permission.

    THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
    IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
    OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
    IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
    INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
    NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
    DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
    THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
    (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
    THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/